name: Add issues with tasks to the project board

on:
  workflow_dispatch:
  # issues:
  #   types:
  #     - labeled

jobs:
  add-to-project-board:
    name: Add issue to VRWA project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/VERSO-UVM/projects/26
          labeled: backend, frontend
          github-token: ${{ secrets.GITHUB_TOKEN }} # TODO: Get and set token with correct permissions
          label-operator: OR
  add-to-team-board:
    name: Add issue to RIP Project Board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/VERSO-UVM/projects/25
          labeled: backend, frontend
          github-token: ${{ secrets.GITHUB_TOKEN }} # TODO: Get and set token with correct permissions
          label-operator: OR
